### ISSUE TITLE
PlotCoverageByCell

### ISSUE THREAD

**Issue by Puriney** [crazyhottommy/scATACutils#2]
Hello,
I was wondering if the `PlotCoverageByCell` is the function to visualize the presence of the fragments along the genome per cell? Like the lower panel in the 
<img width="596" alt="Screen Shot 2020-06-13 at 3 53 00 PM" src="https://user-images.githubusercontent.com/1233372/84578809-266f2180-ad8e-11ea-9e41-8b69d93e91aa.png">
figure here:

**Comment by crazyhottommy** [comment]
yes. I will need to work a bit to make it (the bottom) align with the pile-up tracks (the top).

**Comment by Puriney** [comment]
Thank you. I asked because i did not see the example rendered at the README.

**Comment by Puriney** [comment]
I happened to need this function recently but I did not find a solution. I was writing something using Signac and geom_tile. I am not confident because the tiles are not that visible as the paper does. @crazyhottommy If possible, I was wondering if you could help to examine the implementation here? https://github.com/timoast/signac/issues/166 Many thanks.

![covplot](https://user-images.githubusercontent.com/1233372/84580060-20327280-ad99-11ea-909b-b7fc77044b1b.png)

**Comment by crazyhottommy** [comment]
I just updated the README and you can see the rendering. I have not had time to read carefully about your code. One thing to note is that for this type of plotting, use the paired-end fragment for visualization, do not use the cut-site itself.

**Comment by Puriney** [comment]
Thank you. Really looking forward to your package.
